---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vngcloud-csi-node-role
  labels:
    {{- include "vngcloud-blockstorage-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get"]
