apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vngcloud-csi-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vngcloud-blockstorage-csi-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: vngcloud-csi-controller
      {{- include "vngcloud-blockstorage-csi-driver.selectorLabels" . | nindent 6 }}
  {{- if le (.Values.controller.replicaCount | int) 2 }}
  maxUnavailable: 1
  {{- else }}
  minAvailable: 2
  {{- end }}
