---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vngcloudAccessSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vngcloud-blockstorage-csi-driver.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.vngcloudAccessSecret.keyId | b64enc | quote }}
  accessKey: {{ .Values.vngcloudAccessSecret.accessKey | b64enc | quote }}
  identityEndpoint: {{ .Values.vngcloudAccessSecret.identityEndpoint | b64enc | quote }}
  vserverEndpoint: {{ .Values.vngcloudAccessSecret.vserverEndpoint | b64enc | quote }}
  vksClusterId: {{ .Values.vngcloudAccessSecret.vksClusterId | b64enc | quote }}