apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ingressControllerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Values.ingressControllerName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.ingressControllerName }}
  serviceName: {{ .Values.ingressControllerName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.ingressControllerName }}
    spec:
      serviceAccountName: vngcloud-ingress-controller
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.webhook.enabled }}
        - args:
          - /bin/vngcloud-ic-webhook
          - --create-secret=true
          - --common-name={{ .Values.webhook.name }}
          - --port-https={{ .Values.webhook.portHttps }}
          - --namespace={{ .Release.Namespace }}
          env:
          - name: TLS
            value: "true"
          - name: LOG_LEVEL
            value: debug
          - name: LOG_JSON
            value: "true"
          image: "{{ .Values.webhook.image }}:{{ default .Chart.AppVersion .Values.webhook.tag }}"
          imagePullPolicy: {{ .Values.webhook.pullPolicy }}
          name: vngcloud-ic-webhook
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: kubernetes-config
            readOnly: true
        {{- end }}
        - name: {{ .Values.ingressControllerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /bin/vngcloud-ingress-controller
            - -v={{ .Values.logVerbosityLevel }}
            - --config=/etc/config/vngcloud-ingress-controller-config.yaml
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubernetes-config
              readOnly: true
            - name: ingress-config
              mountPath: /etc/config
      hostNetwork: true
      volumes:
        - name: kubernetes-config
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: ingress-config
          secret:
            secretName: {{ .Values.secret.name }}
            items:
              - key: config
                path: vngcloud-ingress-controller-config.yaml