name: Push Chart to vCR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.1.0

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }} --username ${{ github.repository_owner }} --password-stdin
          echo ${{ secrets.VCR_PASSWORD }} | helm registry login vcr.vngcloud.vn --username ${{ secrets.VCR_USER }} --password-stdin

      - name: save helm chart to local registry
        run: |
          find . -name "*.tgz" -type f -delete
          echo ${{ github.workspace }}
          cd ${{ github.workspace }} && helm package ${{ github.workspace }}/charts/*
          cd ${{ github.workspace }} && ./push_tgz.sh oci://ghcr.io/${{ github.repository_owner }}/vks-helm-charts
          cd ${{ github.workspace }} && ./push_tgz.sh oci://${{ secrets.VCR_REPO }}/vks-helm-charts
